title: Pablo Felgueres 
email: pablofelgueres@gmail.com
description: "" # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pablofelgueres.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pfelgueres 
github_username: felgueres 

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
